name: ci

on:
  pull_request:
    branches: [ main ]

jobs:
  style:
    name: style
    runs-on: ubuntu-latest

    steps:
      - name: Go setup
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      
      - name: staticcheck setup
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run style checks
        run: |
          test -z $(go fmt ./...)
          staticcheck ./...
  
  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Go setup
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: go test ./... -cover